const footnotes: string[] = [
    'Jim Byers. “Huge Transit Expansion Announced for Metro.” Toronto Star, April 5, 1990, sec. A1.',
    'Byers. “Huge Transit Expansion Announced for Metro.” sec. A1; Peter Howell. “\'Finch Loop\' Proposed as Subway Expansion.” Toronto Star, March 6, 1990, sec. A1.',
    'Byers. “Huge Transit Expansion Announced for Metro.” sec. A1; Canada. Ontario. UMA Engineering Ltd., Metropolitan Toronto Planning Department, Ministry of Transportation, Ministry of the Environment; Environmental Assessment Branch, Toronto Transit Commission. Let’s Move Program Overview Report. Toronto, 1990, 13.',
    'Byers. “Huge Transit Expansion Announced for Metro.” sec. A1',
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011. Toronto: Toronto Transit Commission, 1985.',
    `Alan Dunlop. Two proposals: The photo at left shows Yonge St. looking south; intersecting with Sheppard Ave. (at cluster of high-rises); where Mel Lastman wants the proposed subway to run. Others want the line further north; at Finch Ave.; near the Xerox building (partially out of the picture above). That line would parallel the hydro right of way (to the right of where the helicopter is circling), 1990, black and white digital, Toronto Star photo archive, Toronto, accessed January 7, 2020, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0106979F&R=DC-TSPA_0106979F`,
    'Peter Howell. “NDP Puts Transit Expansion on Hold.” Toronto Star, October 3, 1990, sec. A3.',
    'Richard, Mackie. “NDP Will Spend $5-Billion to Expand Transit Systems: Government Criticized for Using Plans Initiated by the Liberals.” The Globe and Mail. November 27, 1990, sec. A12.',
    `James Royson. “Attention, Subway Patrons: The TTC Needs More of You.” Toronto Star, December 4, 1993, sec. A1; Rijn and James. “Rae Okays New Lines for Subway 'Grand Slam'.” sec. A1.`,
    `Nicolaas Van Rijn and Royson James. “Rae Okays New Lines for Subway 'Grand Slam'.” Toronto Star, February 9, 1993, sec. A1.`,
    `Rijn and James. “Rae Okays New Lines for Subway 'Grand Slam'.” sec. A1.`,
    'Canada. Ontario. Ministry of the Environment. Eglinton West Rapid Transit Environmental Assessment Report. Toronto: Toronto Transit Commission, 1993.',
    `Dumez Real Estate North American Ltd. Courtesy of Bob Krawczyk. York City Centre Phases 1-3, 1992, colour digital, Architectural Conservancy Ontario TOBuilt photo collection, Toronto, accessed April 17, 2022, https://www.acotoronto.ca/images/buildings/Large/YorkCityCentre.jpg`,
    `Jim Byers. “Huge Transit Expansion Announced for Metro.” Toronto Star, April 5, 1990, sec. A1; Rijn and James. “Rae Okays New Lines for Subway 'Grand Slam'.” sec. A1.`,
    `Rijn and James. “Rae Okays New Lines for Subway 'Grand Slam'.” sec. A1.`,
    `David Lewis Stein. “After $45 Million Is That All There Is?” Toronto Star, February 5, 1993, sec. A27.`,
    `Rijn and James. “Rae Okays New Lines for Subway 'Grand Slam'.” sec. A1.`,
    `Toronto Transit Commission. “Toronto Rapid Transit Expansion Program.” Tunnelling and Underground Space Technology 10, no. 1 (1995): 53–63. https://doi.org/10.1016/0886-7798(95)90002-0.`,
    `Toronto Transit Commission. “Toronto Rapid Transit Expansion Program.” 53–63.`,
    `Toronto Transit Commission. “Toronto Rapid Transit Expansion Program.” 53–63.`,
    `Toronto Transit Commission. “Toronto Rapid Transit Expansion Program.” 53–63.`,
    `Rijn and James. “Rae Okays New Lines for Subway 'Grand Slam'.” sec. A1.`,
    `David Lewis Stein. “Metro Taxpayers Being Taken for a Ride.” Toronto Star, February 21, 1993, sec. B1.`,
    `Stein. “Metro Taxpayers Being Taken for a Ride.” sec. B1.`,
    `James Royson. “Deciding Which Train to Take Metro Council Has to Vote on Subway Expansion. Everyone has a Favorite.” Toronto Star, March 8, 1994, sec. A15.`,
    'Canada. Ontario. UMA Engineering Ltd., Metropolitan Toronto Planning Department, Ministry of Transportation, Ministry of the Environment; Environmental Assessment Branch, Toronto Transit Commission. Let’s Move Program Overview Report, 13.',
    'Ibid.',
    'Ibid.',
    'Tony Bock Full steam ahead: A GO train crosses a typically busy Don Valley Parkway. The transit system has big plans to increase ridership., Toronto Star photo archive, Toronto, accessed February 10, 2021, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0012693F&R=DC-TSPA_0012693F',
    `James Royson. “Metro Has Final Say on 2 Lines, NDP Says.” Toronto Star, October 5, 1994, sec. A6.`,
    `Gail Swainson. “Transit Lines Halted After Two Days of Debate, Plan Defeated 18-12.” Toronto Star, February 24, 1995, sec. A1.`,
    `Bruce Campion-Smith. “How Province Could Take over the TTC But Potential Political Pitfalls in Store Should Queen's Park Override Metro.” Toronto Star, February 25, 1995, sec. A2.`,
    `Bruce Campion-Smith. “Eglinton Subway Project under Way $740 Million Line Will Create Thousands of Jobs, Rae Pledges.” Toronto Star, August 26, 1994, sec. A9; James, Royson. “TTC Backs New Transit Lines 1925 Million to Lay Groundwork for 1994 Start.” Toronto Star, February 17, 1993, sec. A6; James, Royson. “Work Begins on Sheppard Subway Line Metro, Province in Fight over Two Other Lines.” Toronto Star, June 23, 1994, sec. A10.`,
    `Bruce Campion-Smith. “Tories Derail Eglinton Subway But $945 Million Sheppard Line Gets Go-Ahead.” Toronto Star, July 22, 1995, sec. A4.`,
    `Boris Spremo. Canada – Ontario – Toronto – Transit Commission - Subways - Sheppard Subway, 1998, colour digital, Toronto Star photo archive, Toronto, accessed January 7, 2020, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0115683F&R=DC-TSPA_0115683F`,
    `Campion-Smith. “Tories Derail Eglinton Subway.” sec. A4.`,
    `Ibid.`
];

export default footnotes;