const footnotes: string[] = [
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011. Toronto: Toronto Transit Commission, 1985; Mitchell Smith. “TTC Urges $2.7 Billion Expansion.” Toronto Star, October 1, 1985, sec. A19.`,
    `Smith. “TTC Urges $2.7 Billion Expansion.” sec. A19.`,
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, 56.',
    'Ibid, 57.',
    'Ibid, 58.',
    'Ibid, 58.',
    `Michael Smith. “Province Considering New Subway TTC Says.” Toronto Star, April 5, 1987, sec. A3; Smith. “TTC Urges $2.7 Billion Expansion.” sec. A19.`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011. Toronto: Toronto Transit Commission, 1985.`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011.`,
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Metro/TTC Rapid Transit Study. Toronto: Toronto Transit Commission, 1982',
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011.`,
    'Ibid.',
    `Ibid, 14.`,
    `Ibid, 26.`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Downtown Rapid Transit Study. Toronto: Toronto Transit Commission, 1985`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Downtown Rapid Transit Study, 52.`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Downtown Rapid Transit Study, 53.`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, 14.`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Downtown Rapid Transit Study, 50.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, 59.',
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, 50-51.',
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, A2.',
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, A3.',
    'Ibid.',
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, 34.',
    'Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, A3.',
    'Ibid.',
    'Pi.1415926535. MBTA route SL2 bus at World Trade Center station. 2017, colour digital, Wikimedia Commons, Boston, accessed February 13, 2021, https://commons.wikimedia.org/wiki/File:MBTA_route_SL2_bus_at_World_Trade_Center_station,_December_2019.JPG. Creative Commons License (CC BY-SA 3.0), https://creativecommons.org/licenses/by-sa/3.0/deed.en',
    `David Cooper. Canada – Ontario – North York - Yonge St, 1979, black and white digital, Toronto Star photo archive, Toronto, accessed January 14, 2020, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0107105F&R=DC-TSPA_0107105F`,
    `Mitchell Smith. “Tonks Makes Pitch to Keep Subway Plan Alive for Eglinton.” Toronto Star, June 24, 1986, sec. A6.`,
    `Bob Mitchell. “Eglinton Transit Line Gets Top Billing in 2011.” Toronto Star. June 3, 1986, sec. W6.`,
    `Mike Foster. “Metro's the Loser If Network 2011 Put Back on Shelf.” Toronto Star, February 17, 1987, sec. N4.`,
    `Michael Smith. “Ontario Likely to Derail Sheppard Subway, Officials Fear.” Toronto Star, December 26, 1987, sec. A8.`,
    `Peter Howell. “TTC Fighting on Two Fronts Province, Toronto Give It Rough Ride.” Toronto Star, March 12, 1990, sec. A1.`,
    `Alan Dunlop. Scar Town Centre, 1985, black and white digital, Toronto Star photo archive, Toronto, accessed January 7, 2020, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0107997F&R=DC-TSPA_0107997F`,
    `W R Code. “The Strength of the Centre: Downtown Offices and Metropolitan Decentralization Policy in Toronto.” Environment and Planning A: Economy and Space 15, no. 10 (1983): 1361. https://doi.org/10.1068/a151361.`,
    `Code. “The Strength of the Centre,” 1361-1362.  `,
    `Howell. “TTC Fighting on Two Fronts Province, Toronto Give It Rough Ride.” sec. A1.`,
    `Jim Byers. “Huge Transit Expansion Announced for Metro.” Toronto Star, April 5, 1990, sec. A1.`,
    `Byers. “Huge Transit Expansion Announced for Metro.” sec. A1]`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011, 56.`,
];

export default footnotes;