const footnotes: string[] = [
    `Canada. Ontario. Ministry of Transportation and Communications. Urban Transportation Policy for Ontario – A Statement by the Honourable William G. Davis Premier of Ontario. Toronto: Queen’s Printer for Ontario, 1972.`,
    `Canada. Ontario. Ministry of Transportation and Communications. Urban Transportation Policy for Ontario – A Statement by the Honourable William G. Davis Premier of Ontario.`,
    `Ibid.`,
    `Boris Spremo. Expressway fears: The Allen Rd.; above; formerly known as the Spadina Expressway;; was stopped at Eglinton Ave. in the mid-‘70s after public outcry. Some Metro Politicians say transfortation will be the crucial issue over the next three years because of the rail lands development, 1985, black and white digital, Toronto Star photo archive, Toronto, accessed February 23, 2020, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0115155F&R=DC-TSPA_0115155F&searchPageType=vrl`,
    `Canada. Ontario. Ministry of Transportation and Communications. Urban Transportation Policy for Ontario – A Statement by the Honourable William G. Davis Premier of Ontario.`,
    `Ibid.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project. Toronto: Queen’s Printer for Ontario, 1973.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Canada. Ontario. Ministry of Transportation and Communications. Urban Transportation Policy for Ontario – A Statement by the Honourable William G. Davis Premier of Ontario.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project.`,
    `Ibid.`,
    `Ibid.`,
    `Robert, Williamson. “Davis Says Multi-Region Board to Run GO, Buses near Metro.” The Globe and Mail. August 24, 1973, sec. 5.`,
    `Thomas, Coleman. “Germans Back out: Ontario Cancels Plan for Magnetic Trains.” The Globe and Mail. November 14, 1974, page 1.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Pat, McNenly. “Airport Plan to Create a City of 150,000.” Toronto Star, March 3, 1973, sec. A1.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project.`,
    `Ibid.`,
    `Thomas, Coleman. “Half of GO-Urban Plan Won't Be Built Experts Predict.” The Globe and Mail. October 11, 1973, page 47.`,
    `Coleman. “Half of GO-Urban Plan Won't Be Built Experts Predict.” page 47.`,
    `“TTC: 2 Rails Better for GO-Urban.” Toronto Star, November 27, 1973, sec. A4.`,
    `Thomas, Coleman. “GRO 'Declares War' on Godfrey over Expressway.” The Globe and Mail. September 11, 1973, page 5.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project.`,
    `Thomas, Coleman. “Elevated Train System Called 'Flying Coffin' by Skeptical Audience Members in Scarboro.” The Globe and Mail. September 12, 1973, page 1.`,
    `“GO-Urban Stations Will Be Huge, Unsightly in Suburbs, Report Says.” The Globe and Mail. April 22, 1974, page 29.`,
    `Thomas, Coleman. “Group Accuses Queen's Park of Naivete, Extravagance: GO-Urban Stems from Misjudgment of Metro Transit Needs, Street Car Boosters Say.” The Globe and Mail. November 12, 1973, page 5.`,
    `“Delays, Cost Increases Plague GO-Urban Plan.” The Globe and Mail. May 7, 1974, page 5.`,
    `“GO-Urban's Magnet Malfunction Makes Tories Target of Ridicule.” The Globe and Mail. November 8, 1973, page 3; Peter, Mosher. “Trains Won't Be Ready for the CNE: 'Elegance' of GO-Urban Track to Be Sacrificed for $2 Million Saving.” The Globe and Mail. May 22, 1974, page 31.`,
    `“Work behind on GO-Urban, Firm Admits.” The Globe and Mail. May 4, 1974, page 4.`,
    `“Work behind on GO-Urban, Firm Admits.” page 4.`,
    `Thomas, Coleman. “Breakdown at Munich Test Site: Bugs Halt GO-Urban Train, Ontario Visit Off.” The Globe and Mail. October 29, 1974, page 4.`,
    `“GO-Urban's Magnet Malfunction Makes Tories Target of Ridicule.” page 3; Thomas, Coleman. “'Would Be like Fire Blowout': GO-Urban Magnetic Train Having Trouble on Curves.” The Globe and Mail. November 7, 1973, page 1.`,
    `Canada. Ontario. Ministry of Transportation and Communications. GO-Urban – A Government of Ontario Project.`,
    `Coleman. “Germans Back out: Ontario Cancels Plan for Magnetic Trains.” page 1.`,
    `Coleman. “Germans Back out: Ontario Cancels Plan for Magnetic Trains.” page 1.`,
    `Ibid.`,
    `Ibid.`,
    `Thomas, Coleman. “Ontario Revives Old Transit Plan in a Bid to Refurbish Its Image.” The Globe and Mail. January 10, 1975, page 5.`,
    `Coleman. “Ontario Revives Old Transit Plan.” page 5.`,
    `“Costs of Transit System Have Risen $47 Million.” The Globe and Mail. July 14, 1982, page 4.`,
    `Coleman. “Ontario Revives Old Transit Plan.” page 5.`,
    `“Costs of Transit System Have Risen $47 Million.” page 4; David Cooper. Spring is coming. Yes; it is; and that is about as soon as you will get a chance to board one of these new Toronto Transit Commission (TTC) Light Rail Vehicles (LRVs). They are four feet longer and seat three more passengers than the old cars. Until spring - maybe longer - they are being tested over every foot of TTC streetcar track in the Metro area, 1979, black and white digital, Toronto Star photo archive, Toronto, accessed February 16, 2020, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0115612F&R=DC-TSPA_0115612F`,
    `Michael, Moore. “$6 Million Spent on Successor to Magnetic Train as Ontario 'Picks up the Pieces of Krauss-Maffei'.” The Globe and Mail. May 14, 1976, page 1.`,
    `Moore. “$6 Million Spent on Successor to Magnetic Train” page 1.`,
    `Ibid.`,
    `Thomas, Coleman. “GO-Urban Still Alive but End Product Could Change, Official Says.” The Globe and Mail. February 15, 1975, page 1.`,
    `Paul, Palango. “Is Ontario on the Wrong Track?” The Globe and Mail. August 5, 1982, page 7.`,
    `Russwurm, Lani and Nathan Baker. SkyTrain. English ed. ed. Toronto: Historica Canada, 2019.`,
    `Alan Dunlop. Canada - Ontario - Toronto - Transit Commission - Rapid Transit - Scarborough LRT, 1985, colour digital, Toronto Star photo archive, Toronto, accessed February 16, 2020, https://www.torontopubliclibrary.ca/detail.jsp?Entt=RDMDC-TSPA_0115590F&R=DC-TSPA_0115590F`,
];

export default footnotes;