import type { Metadata } from 'next';
import { Noto_Serif } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { ttcBold } from '@/fonts';

const noto = Noto_Serif({
    subsets: ['latin'],
    variable: '--font-noto',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${ttcBold.variable} ${noto.variable}`}>
            <body className={noto.className}>
                <div className="container mx-auto">
                    <Header />
                    <main className="px-4 sm:px-0">{children}</main>
                    <Footer />
                </div>
            </body>
        </html>
    );
}
