const footnotes: string[] = [
    `“Transit City Report.” Transit City Report. Toronto Transit Commission, March 12, 2007. https://web.archive.org/web/20070708160209/http://www.transitcity.ca/index.php?option=com_content&task=view&id=14&Itemid=28&limit=1&limitstart=4.`,
    `“Transit City Report.”`,
    `BillyCabic. TTC 4071, 4022. 2018, colour digital, Flickr, Toronto, accessed March 17th, 2020, https://www.flickr.com/photos/ttc125drewry/41285764171/. Creative Commons License (CC BY-NC 2.0), https://creativecommons.org/licenses/by-nc/2.0/`,
    `“Transit City Report.”.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Wyliepoon. Eglinton LRT Maintenance & Storage Facility. 2019, colour digital, Flickr, Toronto, accessed March 17th, 2020, https://www.flickr.com/photos/wyliepoon/47940095168/in/photolist-2g3iw5Y-2g3ix4b-2g3itzN-cs9kDj-cs9krm-cs9nDf-cs9mby-2g3iunp-cs9nfq-2g3iBK8-cs9mGq-2g3iqpZ-2g3ipcJ-2g3ip2o-2g3iys1-2g3itRE-2g3itMS-2giTTSs-2giUkk5-2giUk3M-2giUp61-2giU4Zg-2giTXV7-2giTUv4-2giUked-2giU5xR-2giU1PZ-2giU1vY-2giUpg1-2giTUPA-2giUjY8-2giUdEg-2g3iohT-2g3iqc4-cs9kML-cs9nth-cs9n3Y-cs9mjC-2g3iski-cs9mRw-2g3ixkP-cs9kZf-2giTUEs-2giTY2u-2giUjV2-2giUjNZ-2giTRep-2giU1ZP-2giU1WN-2giTREu. Creative Commons License (CC BY-NC-ND 2.0), https://creativecommons.org/licenses/by-nc-nd/2.0/`,
    '20.	Youngjin. OC Transpo O Train LRV 1107. 2019, colour digital, Wikimedia Commons, Ottawa, accessed April 2nd, 2021, https://commons.wikimedia.org/wiki/File:OC_Transpo_O_Train_LRV_1107.jpg. Creative Commons License (CC BY-SA 3.0), https://creativecommons.org/licenses/by-sa/3.0/deed.en',
    `Kevin, McGran. “TTC Outlines Plans for Dedicated Bus Lanes; Cheaper to Build than Subways Miller Says Ideas Are Achievable. Plan Puts Buses in Dedicated Lanes.” Toronto Star, January 13, 2005, sec. B01.`,
    `McGran. “TTC Outlines.” sec. B01.`,
    `Vincent, Donovan. “Miller Reveals Transit Plan; Favours Streetcars over Underground No Time to Wait for Subways, He Says.” Toronto Star, October 26, 2006, sec. R11.`,
    `Jeff, Gray. “New Subway about Moving 905 Voters.” The Globe and Mail. March 26, 2007, sec. A13.`,
    `James, Royson. “Cash-Poor Toronto in Transit Limbo.” Toronto Star, January 14, 2005, sec. B03.`,
    `Tess, Kalinowski. “A $17.5B Transit Promise; Premier's Pre-Election Pledge Will Create Jobs, Ease Congestion, Reduce Greenhouse Emissions.” Toronto Star, June 16, 2007, sec. A6.`,
    `Tess, Kalinowski. “Transit Plans Run on Separate Tracks; Regional Draft Offers Alternative to TTC's Light Rail Network.” Toronto Star, September 4, 2008, sec. A1.`,
    `Tess, Kalinowski. “Transit City Full Speed Ahead; Planners Refine Details as First of 7 Proposed Light Rail Lines to Break Ground This Fall.” Toronto Star, March 4, 2009, sec. GT5.`,
    `Kalinowski. “Transit City Full Speed Ahead” sec. GT5.`,
    `Tess, Kalinowski. “$950M For New Light Rail Line; Province and Ottawa Will Fund Sheppard East LRT but Haven't Agreed to Replace Aging Streetcar Fleet.” Toronto Star, May 16, 2009, sec. GT3; Tess, Kalinowski. “Transit Gets $9B Jump-Start; Miller Says Provincial Cash for Light Rail Lines Will Create Jobs, Reduce Pollution and Gridlock.” Toronto Star, April 2, 2009, sec. A1.`,
    `The West End. TTC Line 4 Don Mills Station. 2016, colour digital, Flickr, Toronto, accessed March 17th, 2020, https://www.flickr.com/photos/thewestend/31358221460/. Creative Commons License (CC BY-NC-ND 2.0), https://creativecommons.org/licenses/by-nc-nd/2.0/`,
    `John, Goddard, Rider David, and Kalinowski Tess. “GTA Transit Takes $4 Billion Whack Rapid Transit, Viva Projects under Threat Move to Delay Projects 'beyond Short-Sighted,' Furious Miller Says.” Toronto Star, March 26, 2010, sec. A1.`,
    `Tess, Kalinowski. “Trimmed-down Plan on Track for Approval: Next Stop Metrolinx despite Objection to Longer Timelines.” Toronto Star, May 18, 2010, sec. GT2; Paul, Moloney. “Construction Begins on Sheppard LRT.” Toronto Star, December 22, 2009, sec. GT4.`,
    `Tess, Kalinowski, and Rider David. “'War on the Car Is over': Ford Scraps Transit City: Move Could Leave Toronto on Hook for Millions in Penalties, Wasted Work.” Toronto Star, December 2, 2010, sec. A1.`,
    `Kalinowski. “Trimmed-down Plan on Track for Approval.” sec. GT2.`,
    `Kalinowski and Rider. “'War on the Car Is over'.” sec. A1.`,
    `Tess, Kalinowski, and Benzies Rob. “Some Fear Worst for Transit City: Ford's Team Scheduled to Meet with Senior TTC Staff Wednesday.” Toronto Star, December 1, 2010, sec. GT2.`,
    `Kalinowski and Rider. “'War on the Car Is over'.” sec. A1.`,
    `Natalie, Alcoba. “Metrolinx Gives Rob Ford's Transit Plan a Lift.” National Post. February 6, 2012. https://nationalpost.com/posted-toronto/metrolinx-gives-rob-fords-transit-plan-a-lift.`,
    `Ben, Spurr. “Federal Funding Shuffle Casts Doubt on Sheppard LRT.” Toronto Star. June 23, 2017. https://www.thestar.com/news/city_hall/2017/06/23/federal-funding-for-finch-lrt-casts-doubt-on-sheppard-project.html.`,
    `Mary Crandall. working at the western end. 2019, colour digital, Flickr, Toronto, accessed March 17th, 2020, https://www.flickr.com/photos/57340921@N03/47486040332/in/photolist-2fmbnpj-gAuaQA-gAv6bn-2g3ixbF-2g3ivuu-2g3it5n-2g3irmK-2g3irKd-2g3ih5T-2g3ihHG-2g3ii5t-2g3io5y-2g3imr4-2g3inXE-2g3inah-2g3iu2T-2g3ij7U-ebTUWE-2g3ijrB-2g3iunp-2g3itRE-2g3is6D-2g3ivVC-2g3ion8-2g3ipcJ-2g3ixBd-2g3izjr-2g3iptW-2g3ixU2-2g3iz9g-2g3iwFn-2g3iABw-2g3iBK8-2g3iBWa-2g3iBS2-2g3irP2-2g3iqpZ-2g3iqc4-2g3ivyh-2g3ikUr-2g3iv73-2g3iuVS-2g3iu5Z-2g3ioWE-2g3io6w-2g3isf6-2g3irPb-2g3ihcb-2g3ivpu-2g3ip2o/. Creative Commons License (CC BY-NC-ND 2.0), https://creativecommons.org/licenses/by-nc-nd/2.0/`
];

export default footnotes;