const footnotes: string[] = [
    `Canada. Ontario. City of Toronto. Transit Expansion Program – Status Update. Toronto: City of Toronto, 2019, https://www.toronto.ca/legdocs/mmis/2019/ex/bgrd/backgroundfile-131525.pdf`,
    `“Ten-to-One Vote Given TTC Project.” The Globe and Mail. January 2, 1946, sec. 1.`,
    `“Ten-to-One Vote Given TTC Project.” sec. 1.`,
    `“City Can't Have Subway Plans Till Next Year.” The Globe and Mail. May 27, 1955, sec. 5.`,
    `Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011. Toronto: Toronto Transit Commission, 1985.`,
    `Jim Byers. “Huge Transit Expansion Announced for Metro.” Toronto Star, April 5, 1990, sec. A1.`,
    `Canada. Ontario. City of Toronto. Transit Expansion Program – Status Update; Canada. Ontario. Metropolitan Toronto. Metropolitan Toronto Technical Transportation Planning Committee. Network 2011. Toronto: Toronto Transit Commission, 1985.`,
    `Canada. Ontario. Metrolinx. The Big Move. Toronto: Ontario Government, 2008.`,
    `Canada. Ontario. Metrolinx. The Big Move.`,
    `Canada. Ontario. Metrolinx. The Big Move Baseline Monitoring Report. Toronto: Ontario Government, 2013.`,
    `Canada. Ontario. City of Toronto. City Planning Division. Developing Toronto’s Transit Network Plan: Phase 1 – Relief Line Project Assessment. Toronto: City of Toronto, 2016; Canada. Ontario. City of Toronto. Toronto Transit Commission. Downtown Rapid Transit Expansion Study. Toronto: Toronto Transit Commission, 2012.`,
    `Canada. Ontario. City of Toronto. Transit Expansion Program – Status Update.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Sean Marshall. Moss Park and Regent Park, 2018, colour digital, Flickr, Toronto, accessed January 19, 2020, https://www.flickr.com/photos/7119320@N05/38860072644/in/photostream/. Creative Commons License (CC BY-NC 2.0), https://creativecommons.org/licenses/by-nc/2.0/`,
    `Canada. Ontario. City of Toronto. Transit Expansion Program – Status Update.`,
    `Canada. Ontario. City of Toronto. Transit Expansion Program – Status Update.`,
    `Ben, Spurr. “Relief Line Subway Riders' Priority, Poll Shows: Scarborough the Exception, as 44% of Residents There Want Extension to Their Area.” Toronto Star, February 10, 2018, sec. A18.`,
    `Spurr. “Relief Line Subway Riders' Priority.” Toronto Star, sec. A18.`,
    `Ben, Spurr. “Toronto Will Get Billions for Transit: $9B Funding Boost over 10 Years after Province Agrees to Match Ottawa's Infrastructure Plan.” Toronto Star, March 15, 2018, sec. A1.`,
    `Jeff, Gray. “Ontario Government Commits $150-Million for Planning of Downtown Relief Line.” The Globe and Mail. June 2, 2016, sec. A5.`,
    `Jennifer, Pagliaro. “Council Backs Mayor's Road Tolls: Plan Could Begin as Soon as 2019 and Be Fully in Place by 2024.” Toronto Star, December 14, 2016, sec. GT1.`,
    `David, Rider, and Pagliaro Jennifer. “Livid Mayor Rips Province's U-Turn on Tolls: 'Shortsighted' Decision Is the Latest Example of Dismissive Treatment by Queen's Park.” Toronto Star, January 28, 2017, sec. A16.`,
    `Ben, Spurr. “Minister Understands the Need for Relief: Transportation Head Says Opening Subway Line before Yonge Extension 'Makes Sense'.” Toronto Star, December 2, 2018, sec. A4.`,
    `Ben, Spurr. “Province Seeks to Upend Subway Plans: Letters to City Signal Radical Changes to Relief Line, Eglinton LRT as Part of Upload Scheme.” Toronto Star, March 27, 2019, sec. A1.`,
    `Ben, Spurr. “No Relief in Sight: Despite Overcrowding on the TTC, a Long-Planned Downtown Relief Line to Ease Pressure on the Yonge Subway Is Still Years Away from Being Built.” Toronto Star, February 4, 2018, sec. A1; Canada. Ontario. Infrastructure Ontario and Metrolinx. Ontario Line Initial Business Case; Rayson Ho. Bloor Subway Station 2, 2010, colour digital, Wikimedia Commons, Toronto, accessed January 19, 2020, https://commons.wikimedia.org/wiki/File:BloorSubwayStation2.jpg. Public Domain.`,
    `Canada. Ontario. Infrastructure Ontario and Metrolinx. Ontario Line Initial Business Case. Toronto: Ontario Government, 2019, http://www.metrolinx.com/en/regionalplanning/projectevaluation/benefitscases/20190725_Ontario_Line_IBC.PDF`,
    `Canada. Ontario. Infrastructure Ontario and Metrolinx. Ontario Line Initial Business Case.`,
    `Ibid.`,
    `Ibid.`,
    `Ibid.`,
    `Ben, Spurr. “Over the Don and under Fort York: Building the 15-Kilometre Ontario Line Could Get Tricky, Engineering Experts Say.” Toronto Star, April 16, 2019, sec. GT1.`,
    `Ben, Spurr. “Ontario Line Plan Shows New Downtown Route: Path Diverges Further from Relief Line Plans, Casting Doubt on Province's Completion Date.” Toronto Star, July 23, 2019, sec. A1.`,
    `Ben, Spurr. “Ford Vows to Guarantee Funding for Ambitious Subway, LRT Expansion: Redrawing the Map.” Toronto Star, April 11, 2019, sec. A1.`
];

export default footnotes;